name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:

    name: >-
      Ruby (${{ matrix.ruby }}) |
      Oracle XE (${{ matrix.oracle }})
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        oracle:
          - 11.2.0.2
          # Oracle Database XE version 18 causes test failures:
          # TIMESTAMP WITH TIME ZONE
          # - 18.4.0
          - 21.3.0
        ruby:
          - 3.2
          - 3.1
          - '3.0'
          - 2.7
          - jruby
          - truffleruby
    env:
      DATABASE_HOST: localhost
      DATABASE_NAME: ${{ matrix.oracle == '11.2.0.2' && 'XE' || 'XEPDB1' }}
      DATABASE_PORT: 1521
      DATABASE_SYS_PASSWORD: Oracle18
      DATABASE_VERSION: ${{ matrix.oracle }}
      LD_LIBRARY_PATH: /usr/lib/oracle/21/client64/lib
      NLS_LANG: AMERICAN_AMERICA.AL32UTF8
      ORACLE_HOME: /usr/lib/oracle/21/client64
      TNS_ADMIN: ./ci/network/admin
      TZ: Europe/Riga

    services:
      oracle:
        image: gvenzl/oracle-xe:${{ matrix.oracle }}
        ports:
          - 1521:1521
        env:
          TZ: Europe/Riga
          ORACLE_PASSWORD: Oracle18
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Download & Install Oracle Instant Client
        uses: ./.github/actions/oracle-instant-client/download-and-install
      - name: Install JDBC Driver
        run: |
          wget -q https://download.oracle.com/otn-pub/otn_software/jdbc/211/ojdbc11.jar -O ./lib/ojdbc11.jar
        if: "startsWith(matrix.ruby, 'jruby')"
      - name: Create database user
        run: |
          ./ci/setup_accounts.sh
      - name: Bundle install
        run: |
          bundle install --jobs 4 --retry 3
      - name: Run RSpec
        run: |
          bundle exec rspec
      - name: Run bug report templates
        if: "false"
        run: |
          cd guides/bug_report_templates
          ln -s ../../lib lib
          ruby active_record_gem.rb
          ruby active_record_gem_spec.rb
